### ISSUE TITLE
How to include login feature as separate module.

### ISSUE THREAD

**Issue by Timothybas** [AhmedVargos/Valorant-Agents#1]
How to include a login feature as a separate module. and how to manage session and nav redirects

**Comment by AhmedVargos** [comment]
I will be creating it as a separate feature module and using it normally but will be caching the user in my local DB through a core module will probably also create a new core module to handle the actions related to the session ex: editing, logout as it's a more commonly used across other modules.

In regards to using it with the Navigation component, there are multiple ways that this could be achieved, but I recommend you to check[ this article ](https://itnext.io/android-multimodule-navigation-with-the-navigation-component-99f265de24) as it demonstrates a very robust way to managing the graph even with bottom navigation.


Happy coding!
